!> 哈基米说这个是第 degree 阶的 np 个候选多项式中, 哪个不能被低阶项线性表示出来
!> 这个是用最小二乘法做的, 残差 > 1.0 就是线性独立
subroutine cal_error(nx0, ny0, np, nb, r0, degree)
    use mod_reynolds, only: nr
    use mod_sympoly, only: maxv, mons, monid
    use mod_genpoly, only: norder, btotal
    use mod_fi, only: nfi, fmons, fmonid, nexit
    implicit none
    !> np: 本阶段候选多项式数量
    !> nb: 已知用来拟合的基底项数量
    !> nx0, ny0: 工作矩阵允许的最大行数 (样本数) 和最大列数 (基底数)
    integer, intent(in) :: np, nb, nx0, ny0, degree
    !> r0: 随机生成的核间距向量池
    real(kind=8), intent(in) :: r0(nr, maxv)
    !> 当前方程组行数 (样本构型数), ny: 当前方程组列数 (基底数)
    integer :: nx, ny ! number of data randomly generated
    integer :: i, j, k, iloop, nfi0, i0
    !> matA: 设计矩阵 (design matrix), 存基底在各个样本点的值
    !> vecB: 目标向量, 存新多项式在各个样本点的值
    real(kind=8) :: matA(nx0, ny0), vecB(nx0), coefC(nx0), matAx(nx0, ny0), vecBx(nx0)
    real(kind=8) :: v, error, work(2*nx0*ny0)
    ! matA(nx0,ny0) nx0 is the maximal dimension of samples
    ! matA(nx0,ny0) ny0 is the maximal number of polynomials which contain
    ! the polynomials generated by degree 1 ~ N-1, and the new FIs.
    ! calculate nb samples for the nfi FIs.
    ! matA(1:nb,1:nfi)
    !> nfi0 是在算下面这些东西之前, 已经有的 FI 的总数
    nfi0 = nfi
    nx = nb + 100
    ny = nb
    !> 1. 构建已经存在的 FI 的矩阵列
    !> 将已知的 nfi0 个 FI, 分别在 nx 个随机几何构型 r0 上求值, 填入 matA
    do i = 1, nx
        do j = 1, nfi0
            k = fmonid(j) - 1
            call poly_value(fmonid(j), fmons(1, 1:k, j), fmons(2, 1:k, j), r0(1:nr, i), matA(i, j))
        end do
    end do
    ! add the value of polynomials generated by
    ! the previous FIs
    ! matA(1:nb,nfi+1,nfi+nb)
    !> 2. 构建已经 FI 的乘积项 (secondary invariants) 矩阵列
    !> 乘积项同样可以作为基底去拟合高阶多项式, 将它们的值也填入 matA 的后续列
    do i = 1, nb
        matA(1:nx, nfi0 + i) = 1.d0
        do j = 1, btotal(0, i)
            matA(1:nx, nfi0 + i) = matA(1:nx, nfi0 + i)*matA(1:nx, btotal(j, i))
        end do
    end do
    ! test whether the new polynomials in degree N is a FI,
    ! if it is a FI, add it to matA
    !> 3. 遍历测试第 n 阶新生成的候选多项式 (np 个)
    do iloop = 1, np
        !> 计算当前测试的多项式在 nx 个构型点上的目标值 vecB
        do i = 1, nx
            k = monid(iloop) - 1
            call poly_value(monid(iloop), mons(1, 1:k, iloop), mons(2, 1:k, iloop), r0(1:nr, i), vecB(i))
        end do
        !> 备份 matA 和 vecB, 因为 LAPACK 的 dgles 会在原地覆写矩阵破坏原始数据
        matAx(1:nx, 1:ny) = matA(1:nx, nfi0 + 1:nfi0 + ny)
        vecBx(1:nx) = vecB(1:nx)
        !> 最用最小二乘法求解 matAx * coefC = vecBx
        call lsq(nx, ny, nx0, ny0, matAx, vecBx, coefC, work)
        !> 计算均方根误差 (RMSE)
        error = 0.d0
        do i = 1, nx
            v = 0.d0
            do j = 1, ny
                v = v + coefC(j)*matA(i, nfi0 + j)
            end do
            error = error + ((v - vecB(i)))**2
        end do
        error = (error/real(nx))**(1.d0/2.d0)
        !> 4. 如果 RMSE > 1.0, 那说明现在的基底根本无法拟合它, 它包含全新的非线性信息!
        !> 这就说明找到了一个新的基础不变量 (FI)
        if (error .gt. 1.d0) then
            !> 登记新的 FI
            nfi = nfi + 1
            fmons(:, :, nfi) = mons(:, :, iloop)
            fmonid(nfi) = monid(iloop)
            norder(degree) = norder(degree) + 1
            !> 写到文件里, 所以这个代码是找到一个 FI 写一个 FI 的
            call write_poly(fmonid(nfi), fmons(1, 1:fmonid(nfi) - 1, nfi), fmons(2, 1:fmonid(nfi) - 1, nfi), nfi)
            !-------------------
            !> 动态扩容, 把这个新的 FI 扔进设计矩阵, 作为下一轮测试的基底
            ny = ny + 1
            matA(1:nx, nfi0 + ny) = vecB(1:nx)
            !> 样本库也同步扩容, 防止基底增加导致议程组过拟合, 新增一组核间距
            do i0 = 1, 1
                !> 方程组增加一行
                nx = nx + 1
                !> 在这个新增加的点 r0(nx) 上, 计算所有基础不变量的值填入新行
                do j = 1, nfi0
                    k = fmonid(j) - 1
                    call poly_value(fmonid(j), fmons(1, 1:k, j), fmons(2, 1:k, j), r0(1:nr, nx), matA(nx, j))
                end do
                !> 计算乘积项在新点上的值
                do i = 1, nb
                    matA(nx, nfi0 + i) = 1.d0
                    do j = 1, btotal(0, i)
                        matA(nx, nfi0 + i) = matA(nx, nfi0 + i)*matA(nx, btotal(j, i))
                    end do
                end do
                !> 计算本轮刚刚找到的新 FI 在新点上的值
                do i = 1, nfi - nfi0
                    k = fmonid(nfi0 + i) - 1
                    j = nfi0 + nb + i
                    call poly_value(fmonid(nfi0 + i), fmons(1, 1:k, nfi0 + i), fmons(2, 1:k, nfi0 + i), r0(1:nr, nx), matA(nx, j))
                end do
            end do
            !> 打印找到新的 FI 了
          write (702, '(i6,"*  ",i5,",",i5," in degree ",(i2),",",2x,3(1x,i6),2xes23.16)') nfi, iloop, np, degree, nb, nx, ny, error
            !> 检查是否已经找到了用户在输入文件里指定的当前阶数所需要的总的 FI 的数量, 要不要退出
            i0 = 1
            do i = 1, nexit(0)
                if (nfi .eq. nexit(i)) then
                    i0 = 0
                    exit
                end if
            end do
            if (i0 .eq. 0) exit
            !-------------------
            !do j=1,ny
            !  write(711,*) j,coefC(j)
            !enddo
            !  write(711,*) ""
            ! else
            !do j=1,ny
            !  write(713,*) j,coefC(j)
            !enddo
            !  write(713,*) ""
        else
            !> 残差极小, 说明它是冗余项, 直接扔掉, 只打印日志
            write (702, '(9x,i5,",",i5," in degree ",(i2),","2x,3(1x,i6),2xes23.16)') iloop, np, degree, nb, nx, ny, error
        end if
    end do
end subroutine cal_error

!> 包装一下 LAPACK 的最小二乘法求解器, 求超定方程组 Ac = b
subroutine lsq(m, n, m0, n0, A, B, C, work)
    implicit none
    integer, intent(in) :: m, n, m0, n0
    real(kind=8), intent(inout) :: A(m0, n0), B(m0)
    real(kind=8), intent(out) :: C(m0)
    real(kind=8), intent(inout) :: work(2*m0*n0)
    integer :: info, lwork
    !call dgels('N',m,n,1,A,m0,B,m0,work,-1,info)
    !lwork=int(work(1))
    !> 这里硬编码分配了 dgels 需要的工作内存大小
    lwork = 2*m*n
    !> 调用 LAPACK, 'N' 为不转置矩阵 A
    call dgels('N', m, n, 1, A, m0, B, m0, work, lwork, info)
    !> dgles 的解会覆盖 B 里的前 n 个位置, 这里保存到 C 里
    C(1:n) = B(1:n)
end subroutine lsq
